GET  http://localhost:3001/api/user/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZW1haWwiOiJhaGlhbjMwMDgyMDA1QGdtYWlsLmNvbSIsIm5hbWUiOiJBaGlhbiIsImlhdCI6MTc2NjIyNzQ1OSwiZXhwIjoxNzY2MzEzODU5fQ.NTj1u5VRHIpuK9cnZpiz9qpVeZ8lNsfNCArtRyROO4c

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email" : "ahian30082005@gmail.com",
    "password" : "123"
}